apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version-app
  template:
    metadata:
      labels:
        app: version-app
    spec:
      containers:
      - name: version-app
        image: rickstrand/rickstrand:latest
        ports:
        - containerPort: 80
